Reintroduce Path Sanitization
zip-rs/zip pull request #198
Opened 2020-09-12 10:01 UTC by Plecra

Closes #181

I've kept the old behaviour available through `mangled_name`, for users who actively decided on it. I took the opportunity to give a stronger warning in the documentation, and provide an alternative which I think is more suitable.

This also means we can bring back the `ZipArchive::extract` API, which I now see as effectively complete for 0.5.

Are these API changes enough @jamesmcm ?

(And since you've shown interest in the old API, I'd also like to know which strategy you prefer @aspen 😀 )

2020-09-12 10:26 UTC, jamesmcm commented
Thanks, this is great!

2020-09-23 15:31 UTC, rylev requested changes
Awesome! I have a few changes I'd like to see, and I'd like us to bikeshed the name a bit more, but overall this is great!

2020-09-23 15:31 UTC, rylev commented on src/read.rs
> +    /// Malformed and malicious paths are rejected so that they cannot escape
This should probably say "Malformed or potentially malicious paths".

Perhaps we should make reference to `name_as_child` docs to enumerate the types of paths that will be rejected.

2020-09-23 15:31 UTC, rylev commented on src/read.rs
> +            if (file.name()).ends_with('/') {
Why the `()` around `file.name()`?

2020-09-23 15:31 UTC, rylev commented on src/read.rs
> +    /// This bails on the first error and does not attempt cleanup.
Perhaps we should also mention that this will override existing files if they have the same path as a file in the zip archive.

2020-09-23 15:31 UTC, rylev commented on src/read.rs
> +    pub fn name_as_child(&self) -> Option<&Path> {
Not sure how I feel about the name of the method. Perhaps `relative_name` or `checked_relative_name`. Nothing stands out as clearly better.

2020-11-10 16:41 UTC, Plecra commented
Nice points @rylev. I've renamed the API to `enclosed_name`. It's not perfect, but I don't think we'll come up with something better with more time. I'd like to release 0.5.9 (with this fix) within the next couple days, so lmk if there's an issue

2020-11-10 16:41 UTC, merged