Implement TryFrom<OffsetDateTime> for DateTime
zip-rs/zip pull request #330
Opened 2022-11-18 20:34 UTC by aquacash5

This allows users to use try_into when converting `OffsetDateTime` into `DateTime` and deprecates the previous specialized method.

2023-01-30 18:58 UTC, Plecra commented on src/result.rs
> +pub enum ZipDateTimeError {
Please rename this to `DateTimeRangeError` and make it a unit struct

2023-01-30 19:01 UTC, Plecra commented on src/result.rs
> +            ZipDateTimeError::DateTimeOutOfBounds => write!(fmt, "datetime out of bounds"),
"a date could not be represented within the bounds the MS-DOS date range (1980-2107)"

2023-01-30 19:02 UTC, Plecra commented on src/types.rs
>          if dt.year() >= 1980 && dt.year() <= 2107 {
Use `DateTime::try_from` within this method so we reuse the logic

2023-01-30 19:04 UTC, Plecra requested changes
This is great, thanks! It only makes sense with `Try*` in the prelude these days.

2023-01-31 08:57 UTC, Plecra commented
@zamazan4ik would like to get this in and then publish 0.6.4. If you get the chance to prep the release before me, that'd be fantastic!

2023-01-31 13:56 UTC, aquacash5 commented
@Plecra These should address the changes you requested.

2023-01-31 17:08 UTC, Plecra approved these changes
Thanks!

2023-01-31 17:13 UTC, Plecra commented
Need to run the tests on CI - could you sort out those warnings?

2023-01-31 18:25 UTC, aquacash5 commented
That should fix it. I tried running the commands in the workflow on all the computers I have access to. I don't get any warnings or errors.

2023-02-01 13:59 UTC, Plecra commented
Alright, just rebased that on the clippy fixes :) I think we're left with a couple deprecated references which I can fix up just now...

2023-02-01 14:07 UTC, merged